// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ads-home/Aurora.tsx": () => import("../components/mockups/ads-home/Aurora.tsx"),
  "./components/mockups/ads-home/AuroraLight.tsx": () => import("../components/mockups/ads-home/AuroraLight.tsx"),
  "./components/mockups/ads-home/Editorial.tsx": () => import("../components/mockups/ads-home/Editorial.tsx"),
  "./components/mockups/ads-home/Sunset.tsx": () => import("../components/mockups/ads-home/Sunset.tsx"),
  "./components/mockups/chat-home/Aurora.tsx": () => import("../components/mockups/chat-home/Aurora.tsx"),
  "./components/mockups/chat-home/Editorial.tsx": () => import("../components/mockups/chat-home/Editorial.tsx"),
  "./components/mockups/chat-home/Sunset.tsx": () => import("../components/mockups/chat-home/Sunset.tsx"),
  "./components/mockups/mobile-home/Aurora.tsx": () => import("../components/mockups/mobile-home/Aurora.tsx"),
  "./components/mockups/mobile-home/Editorial.tsx": () => import("../components/mockups/mobile-home/Editorial.tsx"),
  "./components/mockups/mobile-home/Sunset.tsx": () => import("../components/mockups/mobile-home/Sunset.tsx"),
  "./components/mockups/web-home/Aurora.tsx": () => import("../components/mockups/web-home/Aurora.tsx"),
  "./components/mockups/web-home/AuroraLight.tsx": () => import("../components/mockups/web-home/AuroraLight.tsx"),
  "./components/mockups/web-home/Editorial.tsx": () => import("../components/mockups/web-home/Editorial.tsx"),
  "./components/mockups/web-home/Sunset.tsx": () => import("../components/mockups/web-home/Sunset.tsx"),
  "./components/mockups/web-home-v2/ApplePink.tsx": () => import("../components/mockups/web-home-v2/ApplePink.tsx"),
  "./components/mockups/web-home-v2/ApplePurple.tsx": () => import("../components/mockups/web-home-v2/ApplePurple.tsx"),
  "./components/mockups/web-home-v2/Bento.tsx": () => import("../components/mockups/web-home-v2/Bento.tsx"),
  "./components/mockups/web-home-v2/Brutalist.tsx": () => import("../components/mockups/web-home-v2/Brutalist.tsx"),
  "./components/mockups/web-home-v2/Clay.tsx": () => import("../components/mockups/web-home-v2/Clay.tsx"),
  "./components/mockups/web-home-v2/Organic.tsx": () => import("../components/mockups/web-home-v2/Organic.tsx"),
  "./components/mockups/web-home-v2/Saas.tsx": () => import("../components/mockups/web-home-v2/Saas.tsx"),
  "./components/mockups/web-home-v2/Swiss.tsx": () => import("../components/mockups/web-home-v2/Swiss.tsx"),
  "./components/mockups/web-home-v3/Luxe.tsx": () => import("../components/mockups/web-home-v3/Luxe.tsx"),
  "./components/mockups/web-home-v3/Neon.tsx": () => import("../components/mockups/web-home-v3/Neon.tsx"),
  "./components/mockups/web-home-v3/Pop.tsx": () => import("../components/mockups/web-home-v3/Pop.tsx")
};
