kind = "web"
previewPath = "/admin"
title = "Admin Panel"
version = "1.0.0"
id = "Adm1nHiMewoPanel00001"

[[services]]
localPort = 8082
name = "Admin Panel"
paths = ["/admin"]

[services.env]
PORT = "8082"
BASE_PATH = "/admin"

[services.development]
run = "pnpm --filter @workspace/admin run dev"

[services.production]
type = "static"

[services.production.build]
args = ["pnpm", "--filter", "@workspace/admin", "run", "build"]

[services.production.build.env]
NODE_ENV = "production"
